### ISSUE TITLE
cloudscribe SimpleContent site with pages but no blog

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#1]
PostgreSQL database.
The site will contain about 20 content pages to be authored by JNCC, accessible in a hierarchical menu structure.

Include Contact page but no blog.

The site will replace existing site http://uk.chm-cbd.net/  

Site to be hosted on Exegesis data centre - details to come separately.

**Comment by joeaudette** [comment]
I'm surprised you didn't want the blog included since the current site has a news section and blog is pretty much the same as news and can show recent posts on the home page etc.

**Comment by CrispinF** [comment]
@joeaudette it was a definite informed decision by Ulric and Danny. The scope of the site is becoming smaller, and it was felt the twitter feed could provide adequate news/updates. 
I guess we can close this one now!
