### ISSUE TITLE
Redirect Manager

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#10]
@joeaudette to liaise with Jim K and me about which version to use and when to bring this.
I will then add some example redirects to show @ulric-wilson how it works.

**Comment by joeaudette** [comment]
this is completed and deployed

**Comment by CrispinF** [comment]
@ulric-wilson the Redirect Manager is in place and I've added a couple of tests. You can edit the specific redirections here:
https://chm.esdm.co.uk/ConfigurationOverride/Edit/RedirectDefinitions
Note that the config is XML, with a "Validate" button that will check your changes against the schema. This stops you entering invalid configuration, but NB it doesn't prevent you creating bad redirects.  

Note that each redirection requires a block of XML like this:
```xml
    <Redirect>
      <FromPattern>^testredirect2$</FromPattern>
      <ToPattern>uk-and-the-cbd</ToPattern>
      <ReturnStatus>Temporary</ReturnStatus>
      <Notes>Test 2</Notes>
    </Redirect>
```

The ReturnStatus should be set to Temporary while working on the particular entry and only set to Permanent when you are sure it is working correctly.

Be aware that the redirection supports RegEx patterns. To make one specific URL go to another, add ^ to the start and $ to the end of the FromPattern.

 With the examples I have configured, including the one shown above, these two URLs should both take you to the "uk-and-the-cbd" page:
https://chm.esdm.co.uk/testredirect
https://chm.esdm.co.uk/testredirect2

If you did not include the final $ then any URL beginning https://chm.esdm.co.uk/testredirect... would be redirected, and you could capture and forward querystring parameters etc, but that is unlikely to be needed on this site.

Could you test this will meet your needs?

**Comment by jonparsonsjncc** [comment]
Hi @CrispinF I have created a new redirect file
[chm-redirects.txt](https://github.com/jncc/chm-website/files/4879597/chm-redirects.txt)
but when i update and try to click update I get a pop up which says "the authorising policy was not found" so looks like i dont have the admin rights - wonder which is easier for you to add the attached file or set up admin rights - happy either way - taa

**Comment by CrispinF** [comment]
@jonparsonsjncc  could you give me a little more info (screenshot?) on when exactly you see that message?

**Comment by jonparsonsjncc** [comment]
![chm](https://user-images.githubusercontent.com/50585245/86612766-8a10f700-bfa8-11ea-95ed-0222223ac895.JPG)
Hi @CrispinF this is what i see on hover and nothing saves when i click

**Comment by CrispinF** [comment]
Ah sorry @jonparsonsjncc  that suggests there's a problem in my upgrade. Will look into it.

**Comment by CrispinF** [comment]
I have done further work to enable this component in the upgraded site, and deployed to staging and live sites.
However, I can get simple redirects working but not with your querystrings. I've a feeling this isn't supported in .NET Core middleware but I need to check with a colleague.  If not, we'll be able to achieve it in IIS web.config.

**Comment by CrispinF** [comment]
@jonparsonsjncc confirmed, the Redirect Manager currently works only on the main URL not querystrings.
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-3.1 for details!
So I'll take your list and configure them in IIS URL rewrite rules instead.

**Comment by CrispinF** [comment]
OK @johawker @jonparsonsjncc I've turned all your rules into IIS redirects.
If you could test each one on the staging site, just to confirm no errors have crept in, and confirm, next step will be to make them Permanent redirects and apply this to the production site (which I can do simply by copying and pasting across).
e.g. test that https://chm-staging.esdm.co.uk/default.aspx?page=7808 redirects to https://chm-staging.esdm.co.uk/cdb-implementation-wales (etc)

**Comment by johawker** [comment]
@CrispinF We've tested this and its working fine thank you! I think its only the page template that is left and otherwise the website is complete! We are still intending to go live tomorrow so do let us know if there is anything else you need. Many thanks.
@jonparsonsjncc for info

**Comment by CrispinF** [comment]
@johawker that's good to hear. 

Next step I will today move this over to the production site and make them all permanent redirects. In future you will be able to use the Redirect Manager should you change any page URLs. The unexpected thing about the old URLs is they were ALL /default.aspx?page=nnnn   and the Redirect Manager can only work on the bit before the "?". Doh!

Realistically I'm not going to get you the template in time to re-make all pages using it today. I have day full of delivering bits of training and other meetings.  Are you happy to "go live" with content as it is, then use the template to make things more consistent thereafter?

If so, the site should just work on the main address when someone does the DNS at your end, after which I will make a change to allow it to run on https. I'm around all day, though in meetings partly.

**Comment by johawker** [comment]
@CrispinF yes I think thats fine, we will go live as we are and if you let me know as soon as the page template is available I'll update all the pages. I assume that I can update and edit or will i need to remake the pages? If i remake the pages will this disrupt the redirects?
Many thanks for all your help.

**Comment by CrispinF** [comment]
The way the templates work you will need to make a new page. But you will be able to shuffle the "slugs" so that when the new one is ready you remove the existing page and swap in the new one with same URL. The new one can be invisible to externals until you swap it in. @johawker

**Comment by johawker** [comment]
@CrispinF Brilliant, that all makes sense, thank you!

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc just to confirm, the redirects are in place in the production site now.
