### ISSUE TITLE
Hosting to 31/03/2021

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#12]
Just a place-holder issue really, as a reminder the hosting contract runs to 31/03/2020.

Check-list of things to do during set-up phase:

- [x] Create site, database, app pool, IIS bindings, data protections keys
- [x] Site folder permissions - check these are correct
- [x] Set and check http response headers and security settings
- [x] Set up site monitoring on the real address
- [x] Configure offsite backups of database and website folder
- [x] Check after a few days that offsite backups are working
- [x] Record details of hosting in normal manner
- [x] Reconfigure bindings and do LetsEncrypt when we go live

**Comment by CrispinF** [comment]
Emailed Ulric and Danny about renewal.

**Comment by CrispinF** [comment]
Forwarded email about renewal to Jon Parsons.

**Comment by CrispinF** [comment]
@johawker I'm thinking this is still unresolved, unless I've missed an email or PO?  Possible to check?

**Comment by johawker** [comment]
@CrispinF emailed you last week regarding hosting and update, please could you send renewal invoice for period up to 31/03/2021 to @jonparsonsjncc many thanks!

**Comment by CrispinF** [comment]
Thanks @johawker invoice going to Jon and you soon.

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc I've emailed Jon about hosting renewal from 01/04/2021.
