### ISSUE TITLE
"Page not found" page

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#14]
This is our default:
![image](https://user-images.githubusercontent.com/10574730/52859634-2113af80-3125-11e9-94af-ff80d5aacc41.png)
@ulric-wilson please confirm whether that is OK, and if not what would you like?

**Comment by ulric-wilson** [comment]
Is there any logging or notification following a 404 error?  

Is this 404 text editable through CMS UI?

**Comment by CrispinF** [comment]
@ulric-wilson yes 404s are logged and visible to admin here https://chm.esdm.co.uk/systemlog 

The 404 page is not editable, as things stand, as normally it would not need to change after an initial design phase.  It could be customised to pull its content from an editable hidden page, of course, but that would be more work.
