### ISSUE TITLE
Test in IE11, Edge, Chrome, Firefox and Safari.

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#16]
A quick check in each to ensure layout and menus are ok.

**Comment by CrispinF** [comment]
All seems fine in Edge, Chrome and FF.
Note that the Twitter embed is not loading in FireFox due to its blocking of tracking cookies (if I switch this off, it works).
![image](https://user-images.githubusercontent.com/10574730/53596875-b63c8c80-3b98-11e9-8761-c3838dd91ce0.png)

I'm unable to test in Safari as no Mac device available at present. @ulric-wilson are you able to?

**Comment by ulric-wilson** [comment]
No I don't have direct access to a Mac.  I might be able to get a colleague to  test
