### ISSUE TITLE
Restrict editing access

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#17]
The specification asked for access to the editing environment to "be restricted to JNCC ip addresses where possible".
@ulric-wilson 
Given we've enabled two-factor authentication (which each of your editing users can set up for themselves now), would you see i.p. restriction as still being necessary?

**Comment by ulric-wilson** [comment]
Hi @CrispinF  I've just been looking at MFA and it seems to be a global setting for the site but only enforced if HTTPS (which this site will be) and not enforced for administrators - is that right?  Presumably no one gets Admin rights without having their role elevated by another Admin, so MFA enforcement for non-Admins would be enough.

**Comment by CrispinF** [comment]
@ulric-wilson yes I think you're understanding that right.  So can we close this one?

**Comment by ulric-wilson** [comment]
Given my interpretation of security model above is correct then closing.
