### ISSUE TITLE
Contact Form?

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#18]
@ulric-wilson we've added a Contact Form to the site, but actually I realise I am not sure whether you want one?  If not we can easily remove. 
I have configured the form to send any submissions to you and Danny, and this is also easy to change.
In you want an invisible recaptcha to prevent spam, you simply need to enter the public and private keys in Site Settings.

**Comment by ulric-wilson** [comment]
Contact form worth keeping I think - thanks.  I assume the email comment and email address of sender **isn't retained** on the website DB - can you confirm?

**Comment by CrispinF** [comment]
@ulric-wilson that's correct, nothing is retained.
Can we close this one?

**Comment by CrispinF** [comment]
NB this does need an SMTP server/service - see #7
