### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#22]
The error page currently looks like this, but can be changed to your requirements. NB it's unlikely a simple content site like this will actually encounter errors.
![image](https://user-images.githubusercontent.com/10574730/53127912-70117880-355b-11e9-9131-069ae076d626.png)

**Comment by ulric-wilson** [comment]
Crispin - if there is a 500 error is there any notification / email / some other means to be made aware of it so it can be investigated/fixed?  I want to update the text but want to be clear what actions might arise from a 500 error.

**Comment by CrispinF** [comment]
@ulric-wilson any errors will be in the system log visible to admins, and you can filter the log by level.  Currently there is no emailing triggered by log events.

**Comment by CrispinF** [comment]
@ulric-wilson can you give us the text you would like to use?

**Comment by ulric-wilson** [comment]
Text:  "Sorry.  An unexpected error occurred while processing your request.  The error has been logged and will be investigated shortly.  If you continue to receive this error please contact feedback[at]jncc.gov.uk quoting 'UK CHM website'."

**Comment by CrispinF** [comment]
@joeaudette see above. This replaces the small text, everything else to stay the same.

**Comment by joeaudette** [comment]
This is completed and deployed.

**Comment by CrispinF** [comment]
@joeaudette How do we test this!?

**Comment by joeaudette** [comment]
I don't know an easy way to test it. There is not a known way for a user to cause an exception. We could add code to throw an exception, deploy, test, and then remove the code and redeploy but that seems wasteful. I would not leave something in place that can cause an exception.

All we did was override the view and change the text, I have no doubt it will show the new text if an error does occur.

**Comment by CrispinF** [comment]
@ulric-wilson are you happy to close?
