### ISSUE TITLE
Change menu bar and footer area to green

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#39]
Footer text changes to white.
JNCC to provide colour specification.

**Comment by johawker** [comment]
HEX
 #259D2F 
RGB
 37, 157, 47 
HSL
 125, 76%, 38%

**Comment by CrispinF** [comment]
Footer done for next deployment.
Menu bar opens a can of worms with sub-menus - there are three different colours in the drop-down menus. Leaving this for now pending review.

**Comment by johawker** [comment]
@CrispinF If I understand correctly, the three colours currently are white, black and a dark grey, if the top bar and menus go the dark green of the union jack (RGB 30,139,67  or HSL 140°, 64%, 33%), the white selection could go light green ( RGB 216,233,181 or HSL 79°,54%,81%) and the black could go grey (RBG 134, 138, 137 or HSL 165°, 2%, 53%)

Have tried to match those colours to the union jack and let me know if that looks better and, if possible, could you make update the footer colour to be the same (RGB 30,139,67  or HSL 140°, 64%, 33%)?

 I understand this may be more complicated to implement than I am aware of so do let me know if this is too much or if you come up against any further problems. Thank you! 

tagging @jonparsonsjncc for info

**Comment by CrispinF** [comment]
@johawker this should be fine... I just need to track down how/where the styles are actually set!

**Comment by CrispinF** [comment]
@johawker footer colour changed.

**Comment by CrispinF** [comment]
@johawker menu now changed colour and deployed to http://chm-staging.esdm.co.uk/  please review @johawker

**Comment by johawker** [comment]
@CrispinF Colour looks good but I have noticed that when you hover over an item in the submenu the previous menu item goes white e.g. if you go to 'UK and CBD' drop down, hover over 'UK implementation of the CBD' so it extends and then hover over 'UK Biodiversity Framework' then 'UK implementation of the CBD' goes white and you can no longer read it. Could this be made so that the text remains visible (either the text goes black of the colour of the highlight changes)?

**Comment by CrispinF** [comment]
@johawker OK I see what you mean about the menu - this effect:
![image](https://user-images.githubusercontent.com/10574730/86176206-8b5fa100-bb1c-11ea-8ef7-e13a9fc5c405.png)

The previously version also did this - Bootstrap defaults!  
The problem is white highlighting and white text. It's a bit fiddly but I'll take a look.

**Comment by CrispinF** [comment]
@johawker I've failed to resolve this - simply cannot find the boostrap variables that control this. So I'll give some advice on how to avoid it. These nested sub-menus are not great for accessibility, as they are quite hard to use. 
Instead, set the Menu Filter on the grandchildren pages to "breadcrumbs,sitemap,childtree". This will stop them forming sub-sub-menu items, but allow them to appear in the other forms of menu.
You still have to be able to find them. So any/all of the following: add explicit links to them in your content, or allow them to be found via the Site Map page, or on the parent page switch on "Show Child Menu". 
I have done this to demonstrate for all the child pages of https://chm-staging.esdm.co.uk/uk-implementation-of-the-cbd 
and you'll see it avoids the menu colouring problem, plus makes the site better for accessibility. We have even had a a11y test recently that recommended against using any dropdowns at all, but the ones on this site are quite keyboard friendly.
Let me know if this solves things for you?

**Comment by johawker** [comment]
@CrispinF Thanks for this, I think if we combine this approach with the new templeate (when its ready) and put the next pages in the relevant links section on the right hand side, then that works, could you roll this out to the funding pages too? I think those are all the sub-sub-pages on the site! Thanks
