### ISSUE TITLE
Change to fixed width layout instead of full width

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#40]

**Comment by CrispinF** [comment]
Done for next deployment.

**Comment by CrispinF** [comment]
@johawker could you review here? https://chm-staging.esdm.co.uk/ 
I've brought the logos into the fixed width layout as requested.

NB this is a new "staging" site pointing at a copy of the live one made a few days ago - you can use this to experiment with content, and we can take it offline again after "go live" if you want.

**Comment by johawker** [comment]
@CrispinF Great, this is looking good thank you, the width and logos look great
