### ISSUE TITLE
Change contact form target email to Feedback@jncc.gov.uk

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#41]

**Comment by CrispinF** [comment]
Done. Please test.

**Comment by johawker** [comment]
Hi @CrispinF , we have sent a test email via the contact form and the testing function in the back of the website, we have recieved a 'thank you for your email enquiry' email but the enquiry itself has not come through the feedback@jncc.gov.uk

**Comment by CrispinF** [comment]
@johawker I'm _very_ puzzled by this. The configuration should send the email to feedback@jncc.gov.uk as can be seen here (this is the same configuration on staging and live sites):
![image](https://user-images.githubusercontent.com/10574730/86149026-4d9a5280-baf3-11ea-97b0-87791edf3b90.png)

Yet when I use the form the message comes to my work address. If I change the configured target, it makes no difference.
But my email address is not known to the website anywhere (I've searched the configuration and the codebase). I'm wondering if somehow the email is being redirected. Investigating!

**Comment by CrispinF** [comment]
OK @johawker I now understand what was happening... the Contact Form was using a different setting to determine where to send the email from the one I was thinking.
This should now be resolved and ready for you to test again.

**Comment by johawker** [comment]
@CrispinF Tested and its working, thank you!
