### ISSUE TITLE
Replace logo images in header with new ones

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#43]
To be supplied by JNCC

**Comment by johawker** [comment]
![chm-logo-new-web-en](https://user-images.githubusercontent.com/65767813/82669503-78130900-9c33-11ea-8a53-e2f5073a8b1e.png)

Union Jack image emailed file name: shutterstock_134658089 (1).jpg

**Comment by CrispinF** [comment]
Have resized the UJ to 124px height to match the new CHM logo (which has lots of white space top and bottom.

**Comment by johawker** [comment]
@CrispinF Thank you, just wondered if these logos could come inwards align with the new fixed width of the pages? Maybe that this will be part of the new page template, so I may be ahead of the game here!

**Comment by CrispinF** [comment]
Please review on https://chm-staging.esdm.co.uk/ 
NB I've made the UJ disappear on small screens as it was hard to find a way to fit both logos nicely.

**Comment by johawker** [comment]
brilliant thank you!
