### ISSUE TITLE
Home page template: added heading, subheading, link address, link text properties

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#45]
JNCC want the carousel images to have text and a link button (copying an example - to be supplied).
Need to add these properties to the template and render them out into the display.

**Comment by CrispinF** [comment]
Done for next deployment.

**Comment by CrispinF** [comment]
@johawker I've sorted out the carousel captions etc so they are placed better, and work ok on smaller screens - first the subheading disappears, then the heading.
Ready for you to test on the staging site https://chm-staging.esdm.co.uk/

**Comment by johawker** [comment]
@CrispinF thats great thank you, I've looked at this and wondered if it would be possible to double the depth of the carousel and increase that gap beneath it for the text (I've also moved the text below the banner and added some more). Here is an image mock up of what I was thinking:  
![Home page mock up](https://user-images.githubusercontent.com/65767813/86008677-05a2ff00-ba11-11ea-85a3-4b561187c605.png)

**Comment by johawker** [comment]
@jonparsonsjncc any additional thoughts?

**Comment by CrispinF** [comment]
@johawker I don't recall restricting the height of the image... have you tried simply uploading a "taller" image and see what happens?  You might be right of course - let me know.

To increase spacing above the heading and the image you could just add marging e.g. i've just done this:
`<h1 class="mt-5">UK&nbsp;Clearing House Mechanism (CHM) for the Convention on Biological Diversity (CBD)</h1>`
mt-5 means margin-top. Smaller number >>> smaller gap!

Very minor point... for accessibility, ideally hyperlinks should be on text that describes what the link is to, rather than words like "click here" (which can mean some re-phrasing).

**Comment by johawker** [comment]
@CrispinF have checked and you're right about the image size not being restricted, I'll see if I can get something sized up right. Thanks for the tip, I'm aware of the accessibility link text and will try and make sure at least the homepage doesn't have the 'click here' on it. Thanks!

**Comment by johawker** [comment]
@CrispinF I've been having a go at changing the size of the banner and its looking great, with a bigger banner however the text sits at the bottom, would it be possible to change this so its centred accross the images, I also wondered if the find out more button colour could be updated to be the same colour green as the menus. thanks!

**Comment by CrispinF** [comment]
Done for next deployment. @johawker

**Comment by CrispinF** [comment]
Deployed to staging and live @johawker please test

**Comment by johawker** [comment]
@CrispinF looks great thank you
