### ISSUE TITLE
Add left/right patterned borders to site

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#47]
JNCC to provide image(s) and example to copy.

**Comment by johawker** [comment]
example available at: : http://www.humboldt.org.co/es/chmcolombia

**Comment by johawker** [comment]
border image has been sent by email (wildflowers.gif) please add this as a repeating background image

**Comment by CrispinF** [comment]
![wildflowers](https://user-images.githubusercontent.com/10574730/84542798-17d32c80-acf2-11ea-9c1c-8d3979a8ec18.gif)
and uploaded here as emails are easily lost!

**Comment by CrispinF** [comment]
I've done this for next deployment. I found I had to make the image fairly transparent or it become too intrusive.

**Comment by johawker** [comment]
@CrispinF this looks brilliant, thank you!
