### ISSUE TITLE
Server i.p. for DNS

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#48]
62.197.41.144

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc are you able to tell me what time the site will go live?  I'd like to be on hand to configure the HTTPS and check it's working. I'm not 100% sure it will run OK on HTTP without the certificate being done.

**Comment by johawker** [comment]
@CrispinF DNS has been updated and we are waiting for it to propogate

**Comment by CrispinF** [comment]
@johawker still not resolving for me... that's an unusually long time.

**Comment by johawker** [comment]
@CrispinF we are checking everything went through ok with our contact at the CBD, will let you know of any developments :)

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc OK, the address is resolving now and I've sorted out the HTTPS, so I think we're live and operational!

**Comment by jonparsonsjncc** [comment]
Hi Crispin

All looks good with the CHM site – thanks for your work on this

One thing is causing us problems – the staging site https://chm.esdm.co.uk/ has been picked up by google and is coming quite high in the rankings – could you please add a redirect on all pages from this domain to go to the new site

Thanks

Jon


Jon Parsons
Technical Delivery Manager
(DIP DigM)
JNCC, Monkstone House, City Road, Peterborough, PE1 1JY
Tel: 01733 562626, Direct Dial: 01733 866827, Mobile: 07526 497077
Email: jon.parsons@jncc.gov.uk<mailto:jon.parsons@jncc.gov.uk>
Skype: jonparsons

**Comment by jonparsonsjncc** [comment]
Hi Jon

Ah, that’s the risk of doing good SEO!  I wonder how the bots found it though.

Fortunately that’s actually the production site, not the staging one, so the indexed pages will take users to the same exact content. But yes of course I will add a redirect to nudge those links over to the new real address.

I’ll let you know when done.

Crispin

From: Jon Parsons <Jon.Parsons@jncc.gov.uk>
Sent: 10 July 2020 19:22
To: jncc/chm-website <reply@reply.github.com>; jncc/chm-website <chm-website@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Jo Hawker <Jo.Hawker@jncc.gov.uk>; Crispin Flower <CrispinFlower@esdm.co.uk>
Subject: RE: [jncc/chm-website] Server i.p. for DNS (#48)
Importance: High

Hi Crispin

All looks good with the CHM site – thanks for your work on this

One thing is causing us problems – the staging site https://chm.esdm.co.uk/ has been picked up by google and is coming quite high in the rankings – could you please add a redirect on all pages from this domain to go to the new site

Thanks

Jon


Jon Parsons
Technical Delivery Manager
(DIP DigM)
JNCC, Monkstone House, City Road, Peterborough, PE1 1JY
Tel: 01733 562626, Direct Dial: 01733 866827, Mobile: 07526 497077
Email: jon.parsons@jncc.gov.uk<mailto:jon.parsons@jncc.gov.uk>
Skype: jonparsons

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc there's now a redirect from chm.esdm.co.uk onto the real address. Please check this out, then we can close this issue.

**Comment by johawker** [comment]
@CrispinF have tested this and appears to work fine, thanks - tested from google too and redirects to the live website :)
