### ISSUE TITLE
Temporary site address during development

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#5]
I've set up chm.esdm.co.uk pointing at 62.197.41.144 (our web12 server).  
NB This will not be the ip to use when we go live.

**Comment by joeaudette** [comment]
Site is now up and running at https://chm.esdm.co.uk/

Anyone who needs edit access please register on the site and let me know so I can add you to admins role to allow editing.

**Comment by CrispinF** [comment]
@joeaudette I've registered.  I think Ulric is now on leave until next Wednesday, and I don't know whether he has delegated to anyone else. So it might be just us for a few days!

**Comment by joeaudette** [comment]
@CrispinF I've added you to admins role

**Comment by CrispinF** [comment]
Thanks. I'll set up https in a minute. I've set the site to use "yeti", and GB timezone.

**Comment by CrispinF** [comment]
https done, using our wildcard cert.  When the site goes like the new binding will be on 62.197.41.134 and we'll use LetsEncrypt for the cert (and remove the ESDM.co.uk binding).
