### ISSUE TITLE
SMTP server/service

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#7]
When people register or forget their passwords, or when people use the contact form, the site needs to send emails. 
This requires an SMTP server or service.  Can JNCC supply details of what we should use please?  During the development phase we can use an Exegesis service, but this is not appropriate for longer term use once live.

**Comment by CrispinF** [comment]
@joeaudette could you put our settings in for the contact form as well, if convenient.

**Comment by joeaudette** [comment]
@CrispinF the only missing setting to light up the contact form was an email address to receive submissions, I've put your email their for now. Just need a list of who really is to receive them.

**Comment by ulric-wilson** [comment]
We're just looking at AWS SES for SMTP.  I'm liaising with CBD secretariat in Montreal as the DNS holders to check they're happy to add SPF/DKIM records to DNS so we can send the emails from the website domain.

**Comment by CrispinF** [comment]
Another option is to remove the need for emailing entirely, as discussed by phone. We'd hide the contact form and replace with a content page.

**Comment by CrispinF** [comment]
Decisions needed as to whether SMTP is needed, and if so what to use.

**Comment by CrispinF** [comment]
Discussed in meeting 22/05/2020 and agreed this could continue to use Exegesis SMTP service as volumes will be tiny.

**Comment by jonparsonsjncc** [comment]
Hi @CrispinF email for the feedback form to be Feedback@jncc.gov.uk
