### ISSUE TITLE
Provide example home page carousel

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#9]
@joeaudette perhaps a mod to the home page template you did, bringing in the "image gallery" carousel plus a simple content block above and below?

**Comment by joeaudette** [comment]
We already have a template for that, we could easily delete the home page and recreate it with a different template. Or we can make a new home page template copied from that one and add twitter widget. But really I think it is best to get some decisions on the twitter widget first. Which one will we use the js one or the server side one and where should it go. We could do a big footer and put it there so it is on every page or we can keep it in the home page only and then it must be in the template.

**Comment by joeaudette** [comment]
why not just create an extra page for now using the gallery template so there is a page to look at and then if we decide it should go on the home page we can update the home page template. We can make sample pages with different approaches and later delete any un-needed pages.

**Comment by CrispinF** [comment]
@joeaudette good idea. I'll do a gallery page  example then we wait for decisions.

**Comment by CrispinF** [comment]
@ulric-wilson example of image carousel using 2 images ffrom the CBD website, with some borrowed CHM home page content:
https://chm.esdm.co.uk/carousel

**Comment by ulric-wilson** [comment]
Crispin - carousel looks fine to me.  can time each image is displayed and duration of transition be controlled?  transition seems quite abrupt - but only minor niggle.  Thanks
